<?php

namespace Blog\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * postsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postsRepository extends EntityRepository
{
}
